export const equipments = [
  {
    id: 'KIO_01',
    name: 'Kiosk',
    ip: '	192.168.1.10',
    status: 'true',
    statusAction: 'Ngưng hoạt động',
    statusConnect: 'Mất kết nối',
    service: 'Khám tim mạch, Khám mắt...',
  }, {
    id: 'KIO_01',
    name: 'Kiosk',
    ip: '	192.168.1.10',
    status: 'true',
    statusAction: 'Ngưng hoạt động',
    statusConnect: 'Mất kết nối',
    service: 'Khám tim mạch, Khám mắt...',
  }, {
    id: 'KIO_01',
    name: 'Kiosk',
    ip: '	192.168.1.10',
    status: 'false',
    statusAction: 'Hoạt động',
    statusConnect: 'Kết nối',
    service: 'Khám tim mạch, Khám mắt...',
  }, {
    id: 'KIO_01',
    name: 'Kiosk',
    ip: '	192.168.1.10',
    status: 'true',
    statusAction: 'Ngưng hoạt động',
    statusConnect: 'Mất kết nối',
    service: 'Khám tim mạch, Khám mắt...',
  }, {
    id: 'KIO_01',
    name: 'Kiosk',
    ip: '	192.168.1.10',
    status: 'false',
    statusAction: 'Hoạt động',
    statusConnect: 'Kết nối',
    service: 'Khám tim mạch, Khám mắt...',
  }, {
    id: 'KIO_01',
    name: 'Kiosk',
    ip: '	192.168.1.10',
    status: 'true',
    statusAction: 'Ngưng hoạt động',
    statusConnect: 'Mất kết nối',
    service: 'Khám tim mạch, Khám mắt...',
  }, {
    id: 'KIO_01',
    name: 'Kiosk',
    ip: '	192.168.1.10',
    status: 'false',
    statusAction: 'Hoạt động',
    statusConnect: 'Kết nối',
    service: 'Khám tim mạch, Khám mắt...',
  }
  , {
    id: 'KIO_01',
    name: 'Kiosk',
    ip: '	192.168.1.10',
    status: 'true',
    statusAction: 'Ngưng hoạt động',
    statusConnect: 'Mất kết nối',
    service: 'Khám tim mạch, Khám mắt...',
  }, {
    id: 'KIO_01',
    name: 'Kiosk',
    ip: '	192.168.1.10',
    status: 'false',
    statusAction: 'Hoạt động',
    statusConnect: 'Kết nối',
    service: 'Khám tim mạch, Khám mắt...',
  }
]