export const equipments = [
  {
    eqId: 1,
    id: 'KIO_01',
    name: 'Kiosk',
    ip: '	192.168.1.10',
    status: 'true',
    statusAction: 'Ngưng hoạt động',
    statusConnect: 'Mất kết nối',
    service: 'Khám tim mạch, Khám mắt...',
  }, {
    eqId: 2,
    id: 'KIO_01',
    name: 'Kiosk',
    ip: '	192.168.1.10',
    status: 'true',
    statusAction: 'Ngưng hoạt động',
    statusConnect: 'Mất kết nối',
    service: 'Khám tim mạch, Khám mắt...',
  }, {
    eqId: 3,
    id: 'KIO_01',
    name: 'Kiosk',
    ip: '	192.168.1.10',
    status: 'false',
    statusAction: 'Hoạt động',
    statusConnect: 'Kết nối',
    service: 'Khám tim mạch, Khám mắt...',
  }, {
    eqId: 4,
    id: 'KIO_01',
    name: 'Kiosk',
    ip: '	192.168.1.10',
    status: 'true',
    statusAction: 'Ngưng hoạt động',
    statusConnect: 'Mất kết nối',
    service: 'Khám tim mạch, Khám mắt...',
  }, {
    eqId: 5,
    id: 'KIO_01',
    name: 'Kiosk',
    ip: '	192.168.1.10',
    status: 'false',
    statusAction: 'Hoạt động',
    statusConnect: 'Kết nối',
    service: 'Khám tim mạch, Khám mắt...',
  }, {
    eqId: 6,
    id: 'KIO_01',
    name: 'Kiosk',
    ip: '	192.168.1.10',
    status: 'true',
    statusAction: 'Ngưng hoạt động',
    statusConnect: 'Mất kết nối',
    service: 'Khám tim mạch, Khám mắt...',
  }, {
    eqId: 7,
    id: 'KIO_01',
    name: 'Kiosk',
    ip: '	192.168.1.10',
    status: 'false',
    statusAction: 'Hoạt động',
    statusConnect: 'Kết nối',
    service: 'Khám tim mạch, Khám mắt...',
  }
  , {
    eqId: 8,
    id: 'KIO_01',
    name: 'Kiosk',
    ip: '	192.168.1.10',
    status: 'true',
    statusAction: 'Ngưng hoạt động',
    statusConnect: 'Mất kết nối',
    service: 'Khám tim mạch, Khám mắt...',
  }, {
    eqId: 9,
    id: 'KIO_01',
    name: 'Kiosk',
    ip: '	192.168.1.10',
    status: 'false',
    statusAction: 'Hoạt động',
    statusConnect: 'Kết nối',
    service: 'Khám tim mạch, Khám mắt...',
  }
]